version: '2'
services:
  brain:
    container_name: brain-container
    image: brain-image
    build:
      context: .
    volumes:
      - ./:/var/app
    env_file: ./variables.env
    environment:
      - NODE_ENV=development
    ports:
      - "9000:9000"






